### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by cauphenuny** [wierton/socket-based-naive-game#2]
我 fork 了您的仓库，[ycpedef/socket-stg](https://github.com/ycpedef/socket-stg)  
然后我修复了一下 ^c 的bug，加了一些新的功能  

但是现在我发现了一个新的bug  
如果在同一台机器上运行 client 和 server，则不会出现问题。  
如果在一台上运行 ./server，另一台上运行 ./client ，那就有一定概率 client 端无法登陆，但是 server 会显示用户已经登陆。  

因为我现在是一个高中OIer，我不太懂这些专业的内容。  

所以您能不能帮我看一下，谢谢！

**Comment by cauphenuny** [comment]
会报错
```
Inconsistency detected by ld.so: dl-fini.c: 87: _dl_fini: Assertion `ns != LM_ID_BASE || i == nloaded' failed!
```

**Comment by wierton** [comment]
报这个错一般是libc的版本不匹配，猜测你可能是在一台机器上编译了client和server，然后将client或server传到另一台机器上运行了。

另一台机器上的libc和编译时resolve的libc不一致可能会导致这个错误。如果这个猜测没错的话，你可以这样处理：
1. 在哪运行的就在那台机器上编译
2. 将编译机器上的libc.so拷贝到运行机器上进行覆盖，注意同时拷贝libc.so和ld.so，可以通过ldd查看需要覆盖的so路径和版本

**Comment by cauphenuny** [comment]
好的，谢谢！
